# Generated by Django 5.0 on 2024-10-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_types',
            field=models.CharField(choices=[('leader', 'cohort leader'), ('deputy', 'deputy leader'), ('member', 'member')], default='member', max_length=100),
        ),
    ]
